############################################
# Docker Compose — Production (with Traefik)
############################################
#
# Usage:
#   1. Build:  docker compose -f compose.prod.yml build php
#   2. Start:  docker compose -f compose.prod.yml up -d
#
# Same COMPOSE_PROFILES behaviour as development compose.
# In your production .env set:
#   AUTORUN_ENABLED=true
#   SSL_MODE=off          (Traefik handles TLS termination)
#   APP_ENV=production
#   APP_DEBUG=false
#
############################################

name: ${COMPOSE_PROJECT_NAME}

services:

  # ─── Traefik (Reverse Proxy + Automatic TLS) ───────────────────
  traefik:
    image: traefik:${TRAEFIK_VERSION:-v3.4}
    restart: unless-stopped
    command:
      - "--api.dashboard=${TRAEFIK_DASHBOARD:-false}"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      # HTTP entrypoint with global redirect to HTTPS
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      # HTTPS entrypoint
      - "--entrypoints.websecure.address=:443"
      # Let's Encrypt ACME (HTTP-01 challenge)
      - "--certificatesresolvers.le.acme.email=${TRAEFIK_ACME_EMAIL}"
      - "--certificatesresolvers.le.acme.storage=/letsencrypt/acme.json"
      - "--certificatesresolvers.le.acme.httpchallenge.entrypoint=web"
    ports:
      - "${TRAEFIK_HTTP_PORT:-80}:80"
      - "${TRAEFIK_HTTPS_PORT:-443}:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - traefik_certs:/letsencrypt
    networks:
      - app

  # ─── Web Server (PHP-FPM + NGINX) ──────────────────────────────
  php:
    build:
      context: .
      target: production
      args:
        PHP_BASE_IMAGE: ${PHP_BASE_IMAGE}
    image: ${APP_IMAGE}:${APP_IMAGE_TAG:-prod}
    stop_signal: SIGQUIT
    restart: unless-stopped
    env_file:
      - ./.env
    environment:
      # Traefik terminates TLS; keep SSL off inside the container
      SSL_MODE: "off"
      HEALTHCHECK_PATH: "${HEALTHCHECK_PATH:-/up}"
      PHP_OPCACHE_ENABLE: "${PHP_OPCACHE_ENABLE:-1}"
      PHP_MEMORY_LIMIT: "${PHP_MEMORY_LIMIT:-256M}"
      PHP_MAX_EXECUTION_TIME: "${PHP_MAX_EXECUTION_TIME:-99}"
      PHP_UPLOAD_MAX_FILE_SIZE: "${PHP_UPLOAD_MAX_FILE_SIZE:-100M}"
      PHP_POST_MAX_SIZE: "${PHP_POST_MAX_SIZE:-100M}"
      NGINX_CLIENT_MAX_BODY_SIZE: "${NGINX_CLIENT_MAX_BODY_SIZE:-100M}"
      # Enable automations in production
      AUTORUN_ENABLED: "${AUTORUN_ENABLED:-true}"
    volumes:
      # Persist user uploads and runtime files across container rebuilds.
      # On first start, Docker copies the image's storage/ content into the volume.
      - storage_data:/var/www/html/storage
    depends_on:
      mariadb:
        condition: service_healthy
      redis:
        condition: service_healthy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.laravel.entrypoints=websecure"
      - "traefik.http.routers.laravel.rule=Host(`${APP_DOMAIN}`)"
      - "traefik.http.routers.laravel.tls=true"
      - "traefik.http.routers.laravel.tls.certresolver=le"
      - "traefik.http.services.laravel.loadbalancer.server.port=8080"
      - "traefik.http.services.laravel.loadbalancer.server.scheme=http"
    networks:
      - app

  # ─── Task Scheduler ────────────────────────────────────────────
  scheduler:
    image: ${APP_IMAGE}:${APP_IMAGE_TAG:-prod}
    command: ["php", "/var/www/html/artisan", "schedule:work"]
    stop_signal: SIGTERM
    restart: unless-stopped
    env_file:
      - ./.env
    depends_on:
      php:
        condition: service_started
      mariadb:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "healthcheck-schedule"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - app

  # ─── Horizon ───────────────────────────────────────────────────
  horizon:
    profiles: ["horizon"]
    image: ${APP_IMAGE}:${APP_IMAGE_TAG:-prod}
    command: ["php", "/var/www/html/artisan", "horizon"]
    stop_signal: SIGTERM
    restart: unless-stopped
    env_file:
      - ./.env
    depends_on:
      php:
        condition: service_started
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "healthcheck-horizon"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - app

  # ─── Queue Worker ──────────────────────────────────────────────
  queue:
    profiles: ["queue"]
    image: ${APP_IMAGE}:${APP_IMAGE_TAG:-prod}
    command: ["php", "/var/www/html/artisan", "queue:work", "--tries=${QUEUE_TRIES:-3}"]
    stop_signal: SIGTERM
    restart: unless-stopped
    env_file:
      - ./.env
    depends_on:
      php:
        condition: service_started
      mariadb:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "healthcheck-queue"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - app

  # ─── Reverb (WebSocket Server) ─────────────────────────────────
  reverb:
    profiles: ["reverb"]
    image: ${APP_IMAGE}:${APP_IMAGE_TAG:-prod}
    command: ["php", "/var/www/html/artisan", "reverb:start", "--port=${REVERB_SERVER_PORT:-8000}"]
    stop_signal: SIGTERM
    restart: unless-stopped
    env_file:
      - ./.env
    depends_on:
      php:
        condition: service_started
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "healthcheck-reverb"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.reverb.entrypoints=websecure"
      - "traefik.http.routers.reverb.rule=Host(`${REVERB_DOMAIN}`)"
      - "traefik.http.routers.reverb.tls=true"
      - "traefik.http.routers.reverb.tls.certresolver=le"
      - "traefik.http.services.reverb.loadbalancer.server.port=${REVERB_SERVER_PORT:-8000}"
      - "traefik.http.services.reverb.loadbalancer.server.scheme=http"
    networks:
      - app

  # ─── MariaDB ───────────────────────────────────────────────────
  mariadb:
    image: mariadb:${MARIADB_VERSION:-11}
    restart: unless-stopped
    # Character set configured via command (no external config files needed in prod)
    command: ["--character-set-server=utf8mb4", "--collation-server=utf8mb4_unicode_ci"]
    environment:
      MARIADB_ROOT_PASSWORD: "${MARIADB_ROOT_PASSWORD}"
      MARIADB_DATABASE: "${MARIADB_DATABASE}"
      MARIADB_USER: "${MARIADB_USER}"
      MARIADB_PASSWORD: "${MARIADB_PASSWORD}"
    volumes:
      - mariadb_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mariadb-admin", "ping", "-h", "127.0.0.1", "-uroot", "-p${MARIADB_ROOT_PASSWORD}", "--silent"]
      interval: 5s
      timeout: 3s
      retries: 30
    networks:
      - app

  # ─── Redis ─────────────────────────────────────────────────────
  redis:
    image: redis:${REDIS_VERSION:-alpine}
    restart: unless-stopped
    command: ["redis-server", "--appendonly", "yes", "--requirepass", "${REDIS_PASSWORD}"]
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping"]
      interval: 5s
      timeout: 3s
      retries: 30
    networks:
      - app

networks:
  app:
    driver: bridge

volumes:
  mariadb_data:
  redis_data:
  storage_data:
  traefik_certs:
